### PR TITLE
i22–adding website favicon (NER logo) and website title ("NER Project Management")

### PR DESCRIPTION
**Pull request by eshwaribhide**

### CODE REVIEW

**Review by jamescd18 — CHANGES_REQUESTED** [review]
The code looks perfect! The only note I have is let's host the favicon image on our Google drive to keep things together in one place. You could place it in the #BUSINESS -> Software folder.

**Comment by kevinyu328** [comment]
Oops, my bad. I was the one that suggested to host the image on Imgur.

**Comment by eshwaribhide** [comment]
> The code looks perfect! The only note I have is let's host the favicon image on our Google drive to keep things together in one place. You could place it in the #BUSINESS -> Software folder.

**Comment by kevinyu328** [comment]
@jamescd18 For some reason, you aren't able to host the favicon image in Google Drive. Would it be okay to use the image hosted on Imgur instead? The image on Imgur is just the NER logo from the marketing folder in the Google Drive.

**Comment by jamescd18** [comment]
> For some reason, you aren't able to host the favicon image in Google Drive. Would it be okay to use the image hosted on Imgur instead? The image on Imgur is just the NER logo from the marketing folder in the Google Drive.

Oh weird, my bad then, I see why it doesn't work with Google Drive. Yeah let's go ahead and change it back to Imgur and have it use that for now.

**Review by kevinyu328 — APPROVED** [review]

**Review by jamescd18 — APPROVED** [review]
awesome!

**Pull request merged**
