### PR TITLE
i85–create constants.js file, for commonly referenced strings

### PR DESCRIPTION
**Pull request by eshwaribhide**

### CODE REVIEW

**Comment by eshwaribhide** [comment]
oooooohhhh hope i didn't break anything

**Comment by kevinyu328** [comment]
Good idea and initiative, but I kind of feel like this adds unnecessary complications to the code. What do you think @jamescd18?

**Comment by eshwaribhide** [comment]
> Good idea and initiative, but I kind of feel like this adds unnecessary complications to the code. What do you think @jamescd18?

@kevinyu328 I know you asked for thoughts from James, but can you please elaborate on what kinds of unnecessary complications this will add?

**Comment by jamescd18** [comment]
> Good idea and initiative, but I kind of feel like this adds unnecessary complications to the code. What do you think @jamescd18?

Yes, I do think that it adds a bit of complication with a central constants file, but I think the benefits outweigh the complication. (at least so far as the complications I am thinking of) I think this is good to differentiate strings (or other stuff) which are constants from ones that aren't constants. The idea would be to reduce errors in writing strings which should be constants, and make editing them easier.

**Comment by eshwaribhide** [comment]
> > Good idea and initiative, but I kind of feel like this adds unnecessary complications to the code. What do you think @jamescd18?
> 
> @kevinyu328 I know you asked for thoughts from James, but can you please elaborate on what kinds of unnecessary complications this will add?
> 
> Generally, if you are using strings more than once in the code, it is a good idea to declare them once in a constant. I created a file because these strings/constants are used throughout various files in the server-side code. I am not putting all strings into this constants file, just commonly used ones.

To elaborate, by "good idea" I am referring to the specific scenario in which a commonly used string changes. For example, if the name of a table changes, instead of changing all references to the table name in the different files that use it, you can just change it once. There is room for error in these situations. 

**I think to make this more concise, I just want to say: Magic numbers should not be in code.**

**Review by kevinyu328 — APPROVED** [review]
Sounds good!

**Pull request merged**
