### PR TITLE
I119 - Made some fields in lookup card inline

### PR DESCRIPTION
**Pull request by RahulR100**
Some of the fields in the lookup card are now inline to make it more compact and utilize space more efficiently.

### CODE REVIEW

**Review by kevinyu328 — DISMISSED** [review]
I think it looks good! Asking for @jamescd18's review as he was the one who created the issue

**Review by jamescd18 — CHANGES_REQUESTED** [review]
Since this is a front-end change, I always appreciate seeing some screenshots of what the change looks like. Now seeing the changes, I am confident that the duration and budget fields are the only ones I'd like to see placed on the same line. With the WP Name, it simply doesn't look as good squishing it onto two lines when it used to just be one. Project Names have the potential to give rise to the same situation, so I'd like to avoid having that be possible. Thank you for putting this together!

Below is the old way:
Screen Shot 2021-01-23 at 11 58 59 PM

Below is the proposed change: 
Screen Shot 2021-01-23 at 11 59 28 PM

**Comment by RahulR100** [comment]
Ok sure I will keep that in mind and I have committed the new change as seen below:
image

**Review by jamescd18 — APPROVED** [review]
Looks great!

**Pull request merged**
